hopefully final version of datapoints context menu
GVigne/Molonari-2022 pull request #21
Opened 2022-04-11 09:21 UTC by ngiboureau

if the merging is fine we can delete this branch

2022-04-11 11:57 UTC, fabien-ors requested changes
When I right-click on any child item of the point view, the software crashes

2022-04-12 08:03 UTC, fabien-ors commented
If I import the Point035 from Molonari-2022/Molonari_2021/resources/sampling_points/study_2022/Point035 and then I try to open it, I obtain the following error :
`Traceback (most recent call last):
  File "/home/fors/Projets/molonari/Molonari-2022/Molonari_2021/ihm/molonaviz/mainwindow.py", line 283, in importPoint
    point = self.currentStudy.addPoint(name, infofile, prawfile, trawfile, noticefile, configfile) 
  File "/home/fors/Projets/molonari/Molonari-2022/Molonari_2021/ihm/molonaviz/study.py", line 104, in addPoint
    raise CustomError(f"{str(e)}\nPlease choose a different point name") 
errors.CustomError: [Errno 17] Le fichier existe: '../../studies/study_2022/Point035'`

2022-04-13 09:02 UTC, ngiboureau commented
The importing bugs are supposed to be handled now. I quickly achieved IHM1_C5 in this branch because it was few to do

2022-04-13 09:14 UTC, fabien-ors approved these changes

2022-04-13 09:14 UTC, merged