Stop Molonaviz from crashing due to poor parameters or directory choice
GVigne/Molonari-2022 pull request #29
Opened 2022-04-13 13:04 UTC by MaxFressonnet

Molonaviz should not crash anymore when wrongly opening study (more precisecly, when chosing a directory that does not exist and then clicking on 'cancel') or entering nonsensical parameters. I also set the limit values of the parameters.

2022-04-13 13:46 UTC, ngiboureau requested changes
The software crashes after the error message appears when entering permeability > 1 in the compute window.

Besides, most of the time the software crashes when computing

2022-04-14 20:28 UTC, fabien-ors commented
> The software crashes after the error message appears when entering permeability > 1 in the compute window.
> 
> Besides, most of the time the software crashes when computing

When I put a permeability > 1 (i.e. 2) the software shows an error message (great!), but the direct model is still computed :
![image](https://user-images.githubusercontent.com/42615550/163470220-ee67d220-b249-46b0-a5ff-fe5e34458aab.png)

2022-04-29 12:56 UTC, MaxFressonnet commented
I commented the changes in the script, and the model is not computed anymore when an error is raised. Some errors in the parameters are not handled by this version, but some are, so I think it is still usefull to merge this branche.

2022-04-29 14:46 UTC, ngiboureau approved these changes

2022-04-29 14:46 UTC, merged