Import labo, Alexis
GVigne/Molonari-2022 pull request #35
Opened 2022-04-15 09:28 UTC by 20sisca

I have checked that the import labo function is working from scratch with sql online

2022-04-15 12:36 UTC, MaxFressonnet requested changes
The labo directory is indeed inserted into the sql table, but there are two little problems :
 - First, when we select a directory with the Browse button, the labo is inserted into the table even if we don't click on the 'OK' button
 - It doesn't work when we type the path instead of using the browse button

2022-04-20 09:39 UTC, ngiboureau requested changes
Importing labo adds the labo lines but doesn't delete the old ones, leading to too much lines in the sql table.

2022-04-29 14:00 UTC, MaxFressonnet approved these changes

2022-04-29 14:45 UTC, ngiboureau approved these changes

2022-04-29 14:46 UTC, merged